### ISSUE TITLE
add some explanations

### ISSUE THREAD

**Issue by jcolomb** [stesie/geierlein#39]
please write somewhere what "data sender" and "als test sender" means. (Unterschied?)
Beim Übertragungprotocol, "speichern" speichert die Daten, nicht die übertragungsprotocol. Es wäre schön wenn es auch da geschrieben ist, da habe ich es gespeichert und habe jetzt kein pdf für mein Buchhalter (ja ich weiss, ich hätte das testen sollen, vor ich den Program zugemacht habe...).
Es wäre auch praktisch, ein video zu machen (installation und Benutzung auf osX).

Sonst fehlt nur ein "donate" button ;-)
Danke für alles!

**Comment by stesie** [comment]
Hi,

sorry, dass ich nicht früher geantwortet habe, der Issue ist mir irgendwie durchgerutscht :/

Der Unterschied zwischen "Daten senden" und "Als Testfall senden" ist, dass letzteres die Daten als Testfall sendet und keine Verarbeitung beim Finanzamt durchgeführt wird.  Also für Produkt-Fälle auf jeden Fall "Daten senden" verwenden.

Ich habe die Buttons jetzt nach "Übertragung testen" umbenannt.

Der Speichern-Button beim Übertragungsprotokoll Popup speichert bei mir eine HTML-Datei ab.
Ich bedauere, dass ich das nicht direkt nachvollziehen kann.  Wie sieht die gespeicherte Datei bei dir aus?  Sind es wirklich nur die Daten -- oder steht oben eine XSLT-Referenz mit dabei?

Einen Link auf die Donate-Seite (https://stesie.github.io/geierlein/donate.html) habe ich ebenso mit in das Popup aufgenommen.  Danke für den Hinweis :)

Viele Grüße

~stesie

**Comment by stesie** [comment]
... oder meinst du die Datei, die unter $HOME/.taxbird/geierlein/xyzzy0815.default/protos/... abgespeichert wird?

**Comment by jcolomb** [comment]
ahah, was gespeichert ist ist lesbar... Ich glaube es funktioniert aber nicht wenn den app noch geöffnet ist ( der html ist dann mit firefox geöffnet und es geht nicht), oder es gab etwas komisches nur bei mir...

Vielen dank,
Julien
