### ISSUE TITLE
Explanation on the website why Income tax explanation is not possible does not make sense.

### ISSUE THREAD

**Issue by zem** [stesie/geierlein#51]
Or is it just me? 

"Leider ist es immer noch nicht möglich mit Geierlein Jahreserklärungen abzugeben, da das Finanzamt eine Übertragung ohne Verwendung der ERiC Bibliothek verwendet (bei der es sich jedoch um proprietäre Software handelt)."

If ERiC library is not used for the transmission, why is is it impossible?

**Comment by stesie** [comment]
Thanks for pointing this out.  I've rephrased it to

"Leider ist es immer noch nicht möglich mit Geierlein Jahreserklärungen abzugeben, da das Finanzamt eine Übertragung ohne Verwendung der ERiC Bibliothek nicht zulässt (bei der es sich jedoch um proprietäre Software handelt). Es ist momentan leider vollkommen unklar, ob dies eines Tages möglich sein wird."

Hope that makes it clear now :-)

Geierlein cannot use ERiC, but it's required to be used.  Hence it's not possible
