### ISSUE TITLE
2016 not selectable

### ISSUE THREAD

**Issue by falkorichter** [stesie/geierlein#52]
I can´t select 2016
<img width="1136" alt="bildschirmfoto 2016-01-02 um 14 54 59" src="https://cloud.githubusercontent.com/assets/50506/12074675/08e47292-b161-11e5-8f89-54b2b79293e7.png">

<img width="1136" alt="bildschirmfoto 2016-01-02 um 14 57 01" src="https://cloud.githubusercontent.com/assets/50506/12074677/1bd93770-b161-11e5-95c8-fa81bcd77e38.png">

**Comment by stesie** [comment]
yes, you're right - thanks for reporting.  Up to now I did neither test Geierlein wrt. year 2016 compatibility nor check the official Elster documentation for updates.

But there haven't been any changes in there, hence I just whitelisted the year number.

I'll publish a release within shortly

**Comment by falkorichter** [comment]
:+1: If you need someone for beta testing in 2017, feel free to get back to me
