### ISSUE TITLE
Print-Button not working in Google Chrome

### ISSUE THREAD

**Issue by peter-s** [stesie/geierlein#53]
Hi,

my geierlein installation is running as a web application on an apache2-server.
With Firefox all works fine, but when using google chrome as frontend, the "Print"-Button doesn't work.
I assume it's a chrome issue, but may be do you have idea?

Regards
Peter

**Comment by stesie** [comment]
Hi,

sorry for having lost sight of this issue for the last month.

The issue was caused by a cross-domain security measure applied by Google Chrome:

```
The frame requesting access has a protocol of "http", the frame being accessed has a protocol of "data". Protocols must match.
```

... I've now adapted the code to use `window.postMessage` to circumvent this.
