### ISSUE TITLE
"Protokoll nachdrucken" interpretiert XML nicht

### ISSUE THREAD

**Issue by ninjadrm** [stesie/geierlein#56]
Das Log wird mir als XML Plaintext angezeigt. Geierlein V0.9.6 mit Firefox 45.4.0 (Debian Stretch).

**Comment by stesie** [comment]
Hi, habe das gerade mal ausprobieren wollen, also eine Büchse mit Stretch installiert und Protokoll nachgedruckt. Bei mir ist in dem Dialog dann das Protokoll zu sehen, wie es sein soll. Probiert mit dem Firefox ESR 45.5.1, der aktuell in Stretch dabei ist sowie der 45.4.0, wie angegeben.

Kannst du Geierlein bitte mal mit `firefox -app application.ini -jsconsole` starten. Dann kommt ein zusätzliches Dialogfenster, von den Info-Meldungen zu JQuery & Co. nicht irritieren lassen. Dann am besten mal auf "Clear" drücken ... anschließend einmal das Protokoll nachdrucken versuchen, ... und dann schauen ob in dem Dialog eine Fehlermeldung erscheint.
