### ISSUE TITLE
Jahr 2017 geht nicht

### ISSUE THREAD

**Issue by markusreymann** [stesie/geierlein#57]
Ich wollte die Voranmeldung für Januar 2017 ausführen. Bei Übertragung testen erscheint die Mitteilung: "Das Formular enthält noch ungültige Feldwerte, Übertragung  nicht möglich". Rot markiert ist beim Vornameldezeitraum das Jahr 2017.

Was mache ich falsch?

Grüsse,

Markus

**Comment by cebe** [comment]
Das sollte mit commit https://github.com/stesie/geierlein/commit/c41a056cc8f2757cea18ec9caabe67c87ee6d2b9 behoben sein. Wenn du die neuste Version benutzt, sollte es funktionieren.

**Comment by markusreymann** [comment]
Ah, ok. Ich hatte noch die 0.9.6 installiert. Ich habe die aktuelle runtergeladen und es geht. Danke und sorry, für die Mühe.

**Comment by stesie** [comment]
Kein Ding :)
