### ISSUE TITLE
de.elster.zkl.crypto.NoKeyException

### ISSUE THREAD

**Issue by htgoebel** [stesie/geierlein#58]
Hallo, wenn ich eine UStVA übertragen will, erhalte ich folgende Meldung:
```
Die Datenübertragung wurde vom Server abgebrochen:
[070089007|Kommunikationsfehler aufgetreten] (Transferheader)-
de.elster.zkl.crypto.NoKeyException
Fehlercode: 070089007
```
An welcher Stelle hakt es?

Geierlein 0.9.9
firefox 52.1.0
lib64nss3 3.28.4

**Comment by samaRox** [comment]
Gleiches Problem bei uns. 
![image](https://cloud.githubusercontent.com/assets/25846816/25522442/31e59fea-2c03-11e7-9a89-806bf71cd716.png)

Geierlein 0.9.7

**Comment by stesie** [comment]
Hi, danke für den Hinweis.

Problem war, dass ein neues Zertifikat zur Verschlüsselung veröffentlicht hatte -- und das alte zwischenzeitig ablehnt. Mit dem neuen Zertifikat geht alles wieder.

Gefixt in Version 0.9.10  (die geht dann auch mit dem Firefox 53)

**Comment by samaRox** [comment]
Hi,
Danke für den schnellen Fix!

Am 30. Apr. 2017, 21:50 +0200 schrieb Stefan Siegl <notifications@github.com>:
