### ISSUE TITLE
Einstellung: Kann "Datei speichern in"-Pafad nicht ändern

### ISSUE THREAD

**Issue by htgoebel** [stesie/geierlein#59]
Im Einstellungs-Dialog (Preferences) ist bei mir eingetragen:
```
Datei speichern in:
/home/xxxx/.taxbird/geierlein/12345678.default/protos
```
- Im Feld mit dem Pfad ist der Text leicht grau hinterlegt (siehe ![Bild](https://cloud.githubusercontent.com/assets/784161/25522486/5c4812c2-2c03-11e7-9886-4847eebfabd5.png))
- Dieser Pfad existiert und enthält keinen Symlinks.

Wenn ich "Wählen..." klicke, bekomme ich einen erwartungsgemäß einen Dialog "Verzeichnis wählen", das Ergebnis dieser Auswahl wird jedoch nicht in die Preferences übernommen.

**Comment by stesie** [comment]
Hey, sorry, dass ich den Issue aus den Augen verloren habe.

Trotzdem danke für den Hinweis!

**Comment by htgoebel** [comment]
Kein Problem. Ich bin froh, dass es Geierlein überhaupt gibt, da kann ich mit ein paar Kleinigkeiten leben. Aber um so schöner, wenn es jetzt behoben ist. Danke :-)
