### ISSUE TITLE
Certificate Exception

### ISSUE THREAD

**Issue by fscz** [stesie/geierlein#60]
When I try to send data I get an exception popup, saying: 
Die Datenübertragung wurde vom Server abgebrochen: 
[070089007|Kommunikationsfehler aufgetreten] (Transferheader)-de.elster.zkl.crypto.NoKeyException
Fehlercode: 070089007

**Comment by samaRox** [comment]
Have you updated your version to 0.9.10? This issue was fixed in this version.

**Comment by fscz** [comment]
updating fixed the issue. thanks
