### ISSUE TITLE
[Javascript Anwendung] Bei der Übertragung ist ein Fehler aufgetreten. 

### ISSUE THREAD

**Issue by jottr** [stesie/geierlein#61]
`git pull` auf die neueste Version, beim "Daten senden" kommt folgender Fehler:

![bildschirmfoto 2017-10-08 um 16 38 26](https://user-images.githubusercontent.com/2744198/31317796-73996be6-ac47-11e7-82bb-e3bcf2c5755c.png)

Ins `log`-file hat geierlein leider nichts geschrieben.

**Comment by stesie** [comment]
hmm, eigentlich hat sich an der Übertragung in letzter Zeit nichts geändert. Gerade auch mit einer Testübertragung probiert und hat hier funktioniert.

Um dem Problem näher zu kommen, kannst du bitte mal die Datei `chrome/content/lib/geierlein/transfer.js` öffnen und oberhalb Zeile 60 (oberhalb von `callback(false)` eine weitere Zeile `alert(err);` einfügen!?
Aktuell wird die Meldung leider nicht augegeben

**Comment by jottr** [comment]
Der `alert` an der Stelle hat nichts ausgegeben. 
Ich hatte geierlein immer wie folgt gestartet: `/Applications/Firefox.app/Contents/MacOS/firefox -app application.ini -load geierlein.rc` - die `geierlein.rc` hat sich aber in Luft aufgelöst, oder war nie vorhanden. 
Ich lade die `geierlein.rc` jetzte einfach nicht mehr, und es geht wieder.
