### ISSUE TITLE
Elster Backend-Konfiguration

### ISSUE THREAD

**Issue by dynamicpete** [stesie/geierlein#65]
Moin!

Nur zur Info:
Zur Konfiguration als Web-App (reverse Proxy) werden in der Wiki (https://github.com/stesie/geierlein/wiki/Apache2-configuration) 
IP-Adressen der Elste-Backendserver gelistet. Diese scheinen sich aber mittlerweile geändert zu haben.
Mit folgenden Einstellungen sollte es aber immer funktionieren:
```
<Proxy balancer://elsterhosts>
       BalancerMember http://datenannahme1.elster.de:80
       BalancerMember http://datenannahme2.elster.de:80
       BalancerMember http://datenannahme3.elster.de:80
       BalancerMember http://datenannahme4.elster.de:80
</Proxy>
```

Gruß Peter

**Comment by stesie** [comment]
oh, guter Punkt :-)

... hab's mal ausgebessert. Danke für den Hinweis
