### ISSUE TITLE
Nicht kompatibel mit Firefox 59.x

### ISSUE THREAD

**Issue by xinelope** [stesie/geierlein#66]
Um Geierlein nutzen zu können musste ich Firefox auf 58 downgraden. Ist ein Update für FF 59.x in Sicht?
LG

**Comment by stesie** [comment]
also ich habe grundsätzlich vor mich darum zu kümmern; nachdem Mozilla aber ein paar Veränderungen an der Firefox API vorgenommen hat, muss ich da ein bissl was nachziehen.

Ich ziehe gerade aber auch um, weswegen Zeit leider eher Mangelware ist ...

Kommt also bestimmt, kann aber noch zwei Wochen dauern ...

**Comment by stesie** [comment]
Nachdem die Finanzverwaltung zwischenzeitlich die alte Schnittstelle abgestellt hat, wird die Version für Firefox 59 vermutlich nichts mehr. Der Weg in die Zukunft ist die Electron-basierte Variante, dann muss man auch nicht alle sechs Wochen wegen Firefox ein Update machen.

Weiter in #67

**Comment by xinelope** [comment]
Dann werde ich mal Electron testen. Viel Dank für die tolle Arbeit.

**Comment by stesie** [comment]
Danke für das Feedback :-)
