### ISSUE TITLE
v1.0.0-rc2: npm install: UNABLE_TO_GET_ISSUER_CERT_LOCALLY

### ISSUE THREAD

**Issue by pspoe** [stesie/geierlein#69]
Was haben Sie getan?
* npm aus den Paketquellen der Distribution installiert.
* 'npm install' aufgerufen

Was erwarten Sie?
* geierlein wird nach ./node_modules installiert
* Falls dies ein Problem der lokalen npm-Konfiguration ist sollte README.md einen entsprechenden Hinweis enthalten.

Was ist passiert?
* Die Installation ist mit Fehler UNABLE_TO_GET_ISSUER_CERT_LOCALLY fehlgeschlagen, siehe
[npm-debug.log](https://github.com/stesie/geierlein/files/1994457/npm-debug.log)

**Comment by stesie** [comment]
Das ist kein Problem von Geierlein, sondern von deiner lokalen Node.js/NPM Installation, bzw. eher tiefer in Richtung System...

Ist das ein frisches System?  Evtl. `ca-certificates` Paket nicht installiert?

**Comment by pspoe** [comment]
Am Freitag, 11. Mai 2018, 11:40:38 CEST schrieb Stefan Siegl:
> Das ist kein Problem von Geierlein, sondern von deiner lokalen Node.js/NPM
> Installation, bzw. eher tiefer in Richtung System...
> 
> Ist das ein frisches System?  Evtl. `ca-certificates` Paket nicht
> installiert?

Das ist ein Debian buster/testing, zuletzt vor 3 Tagen upgedated. npm habe ich heute 
installiert, ca-certificates ist vorhanden.

Mit Hilfe von  Stackoverflow habe ich die Lösung gefunden:
   cat /etc/ssl/certs/*.pm > my-certs.pem
   export export NODE_EXTRA_CA_CERTS=/absolute/path/to/my-certs.pem

Nachdem ich noch das Paket node-optimist installiert hatte verschwindet die 
Fehlermeldung, allerdings bekomme ich jetzt

   Error: failed to fetch from registry: https://registry.npmjs.org/types/node

Zuvor, mit 'npm config set registry http://registry.npmjs.org' kam die schöne Fehlermeldung
   npm ERR! 404 'types/node' is not in the npm registry.
   npm ERR! 404 You should bug the author to publish it
   npm ERR! 404 It was specified as a dependency of 'electron'

**Comment by pspoe** [comment]
Installation von node-typescript-types (nur hier wird
'apt-file search types/node' fündig) und

   npm install --save @types/node

bringt auch nichts.

**Comment by stesie** [comment]
Ganz ehrlich, das liegt am Zusammenspiel deines Betriebssystems & NPM.  Viel mehr kann ich dir dazu nicht sagen.

Welches Node hast du eigentlich installiert, bzw. wo kommt dein NPM her? Bei Debian testing ist ja nur "node" selbst dabei, "npm" irgendwie nicht. Das gibt's nur für jessie und sid. Habe ich gerade gesehen: https://packages.debian.org/search?keywords=npm&searchon=names&exact=1&suite=all&section=all
Nicht, dass du da einfach nur eine (inkompatible/alte) Version am System hast ...

... genug der Raterei. Hab's gerade extra mal durchgespielt, mit einem frischen Debian/testing System läuft das einwandfrei durch:

```
$ docker run -ti debian:testing bash
root@a28177550bf4:/# apt-get -yqq git xz-utils wget
E: Invalid operation git
root@a28177550bf4:/# apt-get update
Get:1 http://cdn-fastly.deb.debian.org/debian testing InRelease [143 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian testing/main amd64 Packages [10.0 MB]
Fetched 10.2 MB in 39s (262 kB/s)                                                                                           
Reading package lists... Done
root@a28177550bf4:/# apt-get install -yqq git xz-utils wget
root@a28177550bf4:/# cd /opt
root@a28177550bf4:/opt# wget https://nodejs.org/dist/v8.11.1/node-v8.11.1-linux-x64.tar.xz                                   
--2018-05-11 17:27:40--  https://nodejs.org/dist/v8.11.1/node-v8.11.1-linux-x64.tar.xz
Resolving nodejs.org (nodejs.org)... 104.20.23.46, 104.20.22.46, 2400:cb00:2048:1::6814:172e, ...
Connecting to nodejs.org (nodejs.org)|104.20.23.46|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11337024 (11M) [application/x-xz]
Saving to: 'node-v8.11.1-linux-x64.tar.xz'

node-v8.11.1-linux-x64.tar.xz   100%[====================================================>]  10.81M   308KB/s    in 28s     

2018-05-11 17:28:09 (401 KB/s) - 'node-v8.11.1-linux-x64.tar.xz' saved [11337024/11337024]

root@a28177550bf4:/opt# tar xJf node-v8.11.1-linux-x64.tar.xz 
root@a28177550bf4:/opt# useradd foo
root@a28177550bf4:/opt# mkdir /home/foo
root@a28177550bf4:/opt# chown foo /home/foo
root@a28177550bf4:/opt# su foo
$ bash
foo@a28177550bf4:/opt$ cd
foo@a28177550bf4:~$ git clone https://github.com/stesie/geierlein.git
Cloning into 'geierlein'...
remote: Counting objects: 3716, done.
remote: Compressing objects: 100% (85/85), done.
remote: Total 3716 (delta 59), reused 81 (delta 35), pack-reused 3593
Receiving objects: 100% (3716/3716), 2.72 MiB | 233.00 KiB/s, done.
Resolving deltas: 100% (2086/2086), done.
foo@a28177550bf4:~$ cd geierlein/
foo@a28177550bf4:~/geierlein$ export PATH=/opt/node-v8.11.1-linux-x64/bin/:$PATH
foo@a28177550bf4:~/geierlein$ npm install
npm WARN notice [SECURITY] tunnel-agent has 1 moderate vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=tunnel-agent&version=0.4.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] hoek has 1 moderate vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=hoek&version=2.16.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> electron@1.8.6 postinstall /home/foo/geierlein/node_modules/electron
> node install.js

Downloading SHASUMS256.txt
[============================================>] 100.0% of 5.74 kB (5.74 kB/s)
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-mac@1.8.6 (node_modules/app-builder-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-mac@1.8.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-win@1.8.6 (node_modules/app-builder-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-win@1.8.6: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.2.0 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.2.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 728 packages in 252.511s
```

**Comment by pspoe** [comment]
> Welches Node hast du eigentlich installiert, bzw. wo kommt dein NPM her? Bei
> Debian testing ist ja nur "node" selbst dabei, "npm" irgendwie nicht. Das
> gibt's nur für jessie und sid. Habe ich gerade gesehen:
> https://packages.debian.org/search?
keywords=npm&searchon=names&exact=1&suit
> e=all&section=all Nicht, dass du da einfach nur eine (inkompatible/alte)
> Version am System hast ...

$ dpkg -l nodejs npm
    Name           Version       Architektur  Beschreibung 


$ apt-cache policy nodejs npm
    10.1.0~dfsg-1 1

**Comment by stesie** [comment]
Ahh :)

... das Problem ist, dass das von dir installierte "npm" steinalt ist. Du hast Version 1.4.21, ... das angemoserte `@types/node` ist ein Paket, das zu einem sog. Organisationsaccount gehört ... und die wurden mit npm v.3 eingeführt.  Das ist aber auch schon wieder drei Jahre alt ...

Aktuell ist Version ~6.0

Du kannst entweder dein altes npm verwenden und mit `sudo -H npm -g install npm` zusätzlich eine aktuelle Version installieren (landet dann in `/usr/local/bin`) oder die Binaries von nodejs.org verwenden (und die Debian-Pakete allesamt deinstallieren). Ein `npm install` im Ordner von Geierlein sollte dann ohne Probleme funktionieren.
