### ISSUE TITLE
v1.0.0-rc2 Kein Copy / Paste möglich

### ISSUE THREAD

**Issue by E-VANCE** [stesie/geierlein#71]
Vorab noch mal tausend Dank für diesen großartigen Client, verwende Geierlein jedes Mal mit Freude.

Habe aufgrund der #67 direkt mal die Electron-App (v1.0.0-rc2) auf Mac ausprobiert und soweit alles super, leider kann ich da nicht mehr copy / pasten... Der Pin-Code wurde vom Passwort-Manager generiert und die händische Eingabe ist eher aufreibend 😱

Kann man das einfach aktivieren / enablen?

**Comment by E-VANCE** [comment]
Das scheint an Electron zu liegen, muss erst aktiviert bzw. eingestellt werden --> [siehe hier](https://pracucci.com/atom-electron-enable-copy-and-paste.html)

**Comment by E-VANCE** [comment]
Und mein eigentliches Problem bei der PIN-Eingabe besteht darin, dass ich den backtick nicht verwenden kann (`), bekomme das nicht gesetzt und dadurch stimmt das Passwort nicht...

Keine Ahnung ob das jetzt ebenfalls was mit Electron oder mit dem input / HTML5 zu tun hat aber ich muss den Umweg über die Console nehmen und die input.value per JS setzen um abschicken zu können.

P.S.: Ich könnte das Passwort ändern aber das wäre ja zu einfach 😁

**Comment by stesie** [comment]
Hi, Danke für den Hinweis :) in der 1.0.2 Release gibt's jetzt auch das Menü :)
