### ISSUE TITLE
Encoding Fehler ISO-8859-15

### ISSUE THREAD

**Issue by dssevenit** [stesie/geierlein#72]
Hallo zusammen,

wir bekommen bei der Schnittstelle seit 3-4 Tagen folgende Meldung beim Versuch eine UstVA zu versenden.

> Die Daten konnten nicht verarbeitet werden: Das Encoding der übermittelten Daten entspricht nicht ISO-8859-15

Ist das jemanden bekannt? Liegt es an dem Finanzamt. In google finde ich nur Hinweise von 2015...

Danke

**Comment by stesie** [comment]
es gab da mal eine Mail von der Finanzverwaltung, hab's mir aber noch nicht angesehen. Und eigentlich dachte ich die wollten auf UTF-8 ... aber muss mal bei Gelegenheit gucken

**Comment by dstamou** [comment]
Guten Morgen @stesie 
Danke für die Info, dann ist es zumindest klar warum der Fehler "plötzlich" auftritt.
Ok dann schaue ich auch mal rein. Eventuell finde ich was dazu. Ich gib dann Bescheid falls ich was finde.
Gruß
Dimi

**Comment by dstamou** [comment]
@stesie 

kannst du vielleicht den Inhalt der Mail hier posten bzgl. der nötigen Änderungen?
Würde die Suche nach der Stelle die angepasst werden muss beschleunigen.

Danke

**Comment by stesie** [comment]
Da steht nur, dass  sie ISO-8859-1 ab dem 19.07. nicht mehr annehmen. Vermutlich reicht in der `steuerfall.js` einfach aus `ISO-8859-1` ein `ISO-8859-15` zu machen. Die Zeichensätze sind im Wesentlichen ja ohnehin identisch

**Comment by dstamou** [comment]
Super vielen Dank für die Info @stesie 
Ich schau mal nach.

**Comment by dstamou** [comment]
Hallo @stesie 
es war nur die von dir genannte Änderung notwendig in der steuerfall.js
Danke für die schnelle Hilfe

**Comment by JKramlo** [comment]
Die Datei steuerfall.js kann ich beim besten willen im Mac Paket nicht finden.
Wie kann ich hier dem ISO-Error Abhilfe schaffen?

**Comment by nicmare** [comment]
Ja selbe Problem hier. Laut Code-Suche im Git sollte die Datei hier sein: chrome/content/lib/geierlein/steuerfall.js
Aber wenn ich mir den Paketinhalt der App hier lokal ansehe, finde ich den Pfad nicht. Weiß auch gar nicht mehr wie ich die App installiert habe?! Habe ich schon wieder vergessen ;-)

**Comment by nicmare** [comment]
So jetzt noch mal für die Nullchecker (dazu gehöre ich auch). Habe mich ein wenig in die Thematik eingelesen. Schritt für Schritt:

- den Code von https://github.com/stesie/geierlein downloaden (grüner Button oben rechts)
- entpacken und die Änderung in der Datei steuerfall.js vornehmen
- den terminal starten beginnend von diesem verzeichnis
- npm installieren (falls noch nicht vorhanden)
- npm Befehl ausführen: npm run-script package

Nach ca. 1-2 Minuten findet man im selben Ordner den Suborder "dist/mac". Hier ist unsere geliebte geierlein-app :-) Die schiebt man hin wo man will. typischerweise wo alle anderen Apps/Programme auch sind.

**Comment by JKramlo** [comment]
@nicmare 
Prima, danke hat geklappt. Nach ein bisschen Gefummel um alle "Dependencies" zu haben. ;-)

**Comment by scytho** [comment]
Bei uns hilft alles Ändern in ISO-8859-15 nichts, es kommt immer diese Fehlermeldung.

**Comment by scytho** [comment]
Kein Wunder, ich habe Geierlein nicht per git und npm installiert, sondern mit dem deb-Paket. Kann man da die Zeichenkodierung auch irgendwo ändern?

**Comment by nicmare** [comment]
@scytho ich hab doch genau geschrieben was zu tun ist?!

**Comment by scytho** [comment]
Das ist aber ein anderer Installationsweg. Das muß doch mit dem deb-Paket auch gehen.

**Comment by nicmare** [comment]
Also es führt nun mal derzeit kein Weg dran vorbei, den Sourcecode zu laden und eine App darauf zu kompilieren. Du kannst die App natürlich auch jedesmal per Terminal starten. Finde ich aber umständlich.

**Comment by scytho** [comment]
Da verstehe ich jetzt kein Wort. Die App muß doch gar nicht kompiliert werden. Und wie soll das mit dem Terminal anders laufen?

**Comment by nicmare** [comment]
Na die o. g. marginale Änderung muss am Source vorgenommen werden. Dann kannst du die App per Terminal Befehl starten oder komplizierst eben eine geschlossene App (Paket), die du in die Programme schieben kannst. Habe ich oben beschrieben wie das geht.

**Comment by scytho** [comment]
Den Weg über npm habe ich schon versucht. Es ist aber (unter Linux Mint 18.3) npm 3.5.2 installiert. Da läuft das Skript nicht fehlerfrei durch. Ich versuche gerade herauszufinden, wie man dieses npm aktualisiert bekommt.

**Comment by nicmare** [comment]
kannst den source laden, änderung vornehmen. dann terminal in dem verzeichnis starten dann 
1. npm install 
dann
2. npm start
als Befehle eingeben. Es öffnet sich geierlein

**Comment by scytho** [comment]
Das funktioniert. Dafür mußte ich aber erstmal node usw. komplett vom Rechner werfen und mit nvm die aktuelle Version installieren. Start über Terminal ist aber keine Dauerlösung.

**Comment by nicmare** [comment]
Wenn das geht, kannst du auch einfach statt "npm start", "npm run-script package" ausführen. dann hast du deine dauerhafte lösung in form einer app. jetzt hab ich aber genug geholfen ;-)

**Comment by scytho** [comment]
Das probier ich beim nächsten Mal. Danke. ;-)

**Comment by ananjo** [comment]
@stesie 
8859-15 in steuerfall.js löst das Problem.
Ist das was für einen RC3?
Ohne der Änderung läuft ja gar nichts mit der Übertragung.

Danke

**Comment by stesie** [comment]
ja, habe das schon lange vor, bin nur noch nicht dazu gekommen.  Aber seit gestern im Urlaub, könnte bald was werden :D

**Comment by stesie** [comment]
So, hier ist sie endlich die Release Version 1.0.1 --> https://github.com/stesie/geierlein/releases/tag/v1.0.1

**Comment by ananjo** [comment]
Vielen Dank und einen schönen Urlaub noch!

Grüße

Christian Rackerseder

 

Von: Stefan Siegl <notifications@github.com> 
Gesendet: Freitag, 10. August 2018 13:07
An: stesie/geierlein <geierlein@noreply.github.com>
Cc: ananjo <christian.rackerseder@ananjo.de>; Comment <comment@noreply.github.com>
Betreff: Re: [stesie/geierlein] Encoding Fehler ISO-8859-15 (#72)

 

Closed #72 <https://github.com/stesie/geierlein/issues/72> .
